### ISSUE TITLE
data-order (html5-attribute) attribute is not working.

### ISSUE THREAD

**Issue by mitsuthar** [rweng/jquery-datatables-rails#102]
here is the example of the feature...
http://www.datatables.net/manual/orthogonal-data#HTML-5

data-order seems to be not working. I tried with latest datatables.js and it worked.

example
<td data-order="5000">$ 5000</td>
even after doing that datatable is sorting taking value as a string not with the attribute data-order.

![p1](https://cloud.githubusercontent.com/assets/4837749/3312313/1135cfec-f6d0-11e3-88a4-08b2daebefdb.png)
![p2](https://cloud.githubusercontent.com/assets/4837749/3312315/166d8f2c-f6d0-11e3-8fd5-64588fbd30a7.png)

**Comment by nicekiwi** [comment]
Still no fix for this issues :( really annoying too. 

Even type-hinting the values with (int) doesn't fix it for me. 

It seems to be ignoring data-order's value entirely and just alphabetising the value of the cell. If I place the raw size values in the cells if works fine, but thats not helpful. 

![data-order-fail](https://cloud.githubusercontent.com/assets/738975/5639650/4f5f66f8-967f-11e4-9ff2-090eacc150c2.jpg)

**Comment by nicekiwi** [comment]
@mitsuthar 
please re-open this issue.

**Comment by althaus** [comment]
Stumbled upon the same issue today.

**Comment by Jlesse** [comment]
Also stumbled on this issue. Any news?
