### ISSUE TITLE
Request-URI Too Large

### ISSUE THREAD

**Issue by sujinzhu** [rweng/jquery-datatables-rails#112]
I got error:
Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

I defined 13 columns with dataTable.columnDefs.
Error will disappear when I decrease the quantity of column defines.
[v2.1.10.0.2]

**Comment by m-andreas** [comment]
Maybe its me but I didnt realy get it with this discription. The param "type" must be inside param "ajax"

    "ajax": {
        "url": "your URL ...",
        "type": "POST"
    }
