### ISSUE TITLE
Resizing issues with bootstrap-3 responsive implementation

### ISSUE THREAD

**Issue by zoinks10** [rweng/jquery-datatables-rails#138]
I've installed the bootstrap-3 responsive version of DataTables, and this works fine to re-size the table as I shrink the screen. However it does not work as well when I then expand the screen back to full resolution - it returns to a fixed (small) width after expanding to around 720px wide screens and then will not continue to expand further.

Whilst this is an edge case (I don't re-size my own browser like this unless I'm testing responsiveness), it would be interesting to know what stops it from retuning to the prior full width of the page. Upon screen refresh the width is back to normal.

Thanks for the work on this too - it's great!

**Comment by ricardodovalle** [comment]
Closed due user inactivity.
