### ISSUE TITLE
Could not find generator jquery:datatables:install.

### ISSUE THREAD

**Issue by sunil-sharma** [rweng/jquery-datatables-rails#143]
I have installed gem and tried to run generator:
   rails generate jquery:datatables:install bootstrap3

Its giving me following error : Could not find generator jquery:datatables:install.

**Comment by andela-bbello** [comment]
@ricardodovalle Am still having the generator issue. I couldn't run "rails generate jquery:datatables:install".  I have install with both the version github: 'rweng/jquery-datatables-rails' and '~> 3.2.0'.

**Comment by sunil-sharma** [comment]
@ricardodovalle,  Thanks.

**Comment by emilenriquez** [comment]
still having this problem @2018

**Comment by biju-mouli** [comment]
I am having this issue as well. I used 
    `gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'`

and tried running 
    `rails g jquery:datatables:install`

I get this error:
    `Could not find generator 'jquery:datatables:install'. Maybe you meant 'devise:install', 'responders:install' or 'integration_test'
    Run `rails generate --help` for more options.`
