### ISSUE TITLE
Is there a way to load the views that generate the datatable?

### ISSUE THREAD

**Issue by pablosalgadom** [rweng/jquery-datatables-rails#156]
I need to change the style of the datatable, but i need to change the html a little bit is there a way to do this?

Thanks in advance

**Comment by jh125486** [comment]
What needs to be changed on the HTML?

**Comment by pablosalgadom** [comment]
It was something to accomplish a specific design, but it was solved in other way. This should be closes :)

**Comment by ricardodovalle** [comment]
Thanks @jh125486 and @pablosalgadom :+1: :clap:
