### ISSUE TITLE
Adding a row to datatable

### ISSUE THREAD

**Issue by amitaltizon** [rweng/jquery-datatables-rails#164]
Can we add row to datatable ?

Unable to add row in javascript dynamically.

var t = $('#table').DataTable();
t.row.add( ["1","2","3","4","5"] ).draw();

**Comment by ricardodovalle** [comment]
This gem only add the Datatables jquery to Rails assets path.
Please, ask this question at StackOverflow using the tag DataTables.

Thanks.
