### ISSUE TITLE
Sprockets not able to load css and js files

### ISSUE THREAD

**Issue by sivagollapalli** [rweng/jquery-datatables-rails#166]
Hi 

I am using `rails(4.2)`. I included js and css files as per documentation. But sprockets not able to find css and js files. When I changed file inclusion to following lines then it's start working.
```
# app/assets/stylesheets/application.css.scss
 require dataTables/jquery.dataTables.bootstrap3

# app/assets/javascripts/application.js
//= require dataTables/jquery.dataTables
//= require dataTables/jquery.dataTables.bootstrap3
```
Would there be a mistake in documentation or am I doing anything wrong?

**Comment by ricardodovalle** [comment]
Hi @sivagollapalli , 

Please, post the Gemfile.
The way are you using it is outdated. 

Take look at correct path: https://github.com/rweng/jquery-datatables-rails/tree/master/app/assets/javascripts/dataTables/bootstrap/3

**Comment by ricardodovalle** [comment]
Please, use like: 
````
gem 'jquery-datatables-rails', '~> 3.2.0'
````

You can download the last gem at https://rubygems.org/gems/jquery-datatables-rails and rename the file .gem to .tar and extract it, to see the files and paths.

**Comment by sivagollapalli** [comment]
@ricardodovalle It works for me. I think we need to update this in documentation. Shall I make a PR with this change?

**Comment by ricardodovalle** [comment]
:+1: 
Thank you very much @sivagollapalli.
I will update the documentation.
