### ISSUE TITLE
Pagination Borked

### ISSUE THREAD

**Issue by bradly-swart** [rweng/jquery-datatables-rails#174]
Hi,

So I've followed the railscasts episode 340 to the tee, as well as had a look at the instructions, forums etc for datatables.

I'm using bootsrap3.

For some unknown reason I get duplicate pagination controls in the bottom right, specifically the weird random verticle arrows ??
If I inspect the elements, it highlights the next button as shown in the screen shot. 

I cannot figure out why this is happening, I've tried removing the various style sheets from the application.css, but no luck.

![screen shot 2015-05-07 at 7 33 35 pm](https://cloud.githubusercontent.com/assets/1549672/7512415/2650f2a2-f4f0-11e4-839f-52bdeaaa7041.png)

**Comment by jh125486** [comment]
Those arrows look to be outside `ui.pagination`... can you post more of that DOM below that area?

**Comment by bradly-swart** [comment]
I found the root cause, there is a timepicker plugin called Timepicki that was messing around with the pagination elements, have no idea why so I just deleted the file.

**Comment by bradly-swart** [comment]
going to close this, thanks for having a look at it and responding anyway ;)
