### ISSUE TITLE
Add changelog note for 2.2.3

### ISSUE THREAD

**Issue by pisaacs** [rweng/jquery-datatables-rails#178]
2.2.3 is available on Ruby Gems (https://rubygems.org/gems/jquery-datatables-rails/versions) but I don't see this version listed in the Change Log.

**Comment by ricardodovalle** [comment]
I added a small note, I am sorry and thank you very much.

### 2.2.3
    - updated Commanche responsible plugin.

**Comment by pisaacs** [comment]
Thank you!
