### ISSUE TITLE
pull in the latest datatables fix for triggering isArrayLike issue latest jquery causes

### ISSUE THREAD

**Issue by dstull** [rweng/jquery-datatables-rails#193]
see here for the bug: https://github.com/jquery/jquery/issues/2242

and here for the fix: https://github.com/DataTables/DataTablesSrc/commit/485b259e5c02a

**Comment by dstull** [comment]
I've decided to just pull in datatables directly to my vendor/assets - seems to be working so far and is up to date.  I'm not sure the value this gem provides, other than making install/maintenance easier.  However, if it is not up to date/includes all data tables features, it usefulness diminishes...

**Comment by istana** [comment]
+1 because datatables cannot be used with new jQuery

**Comment by vicvega** [comment]
:+1:

**Comment by cknoxrun** [comment]
It's useful for me as I have it as a gem dependency in an engine. @dstull did you create a PR? If not I will.

**Comment by dstull** [comment]
I have not.

**Comment by mkhairi** [comment]
:+1:

**Comment by benoitwerner** [comment]
+1

**Comment by dometto** [comment]
:+1: is anyone already working on a PR? @rweng, would you accept such a PR and cut a new release?

**Comment by pwim** [comment]
https://github.com/rweng/jquery-datatables-rails/pull/204 updates the assets to 1.10.10, which has the fix for this issue. A new gem. 3.4.0, has also been issued. So I think this issue can be closed now.

**Comment by bartkamphorst** [comment]
Terrific! @pwim Thanks for letting us know. @TigerWolf Appreciate your efforts; thank you! :+1:

**Comment by rweng** [comment]
@dometto sure, I am not actively maintaining this project right now, but pull-requests are always welcome and will be merged in. Might have to ping me once or twice about it, though, sometimes I loose track ;)

@pwin - yep, thank you, I'll close this off then

**Comment by pwin** [comment]
should have been an acknowledgement to @pwim
 -----Original Message-----From: notifications@github.comSent: Sat, 26 Mar 2016 02:33:59 -0700To: jquery-datatables-rails@noreply.github.comSubject: Re: [jquery-datatables-rails] pull in the latest datatables fix for triggering isArrayLike issue latest jquery causes (#193)@dometto sure, I am not actively maintaining this project right now, but pull-requests are always welcome and will be merged in. Might have to ping me once or twice about it, though, sometimes I loose track ;)

@pwin - yep, thank you, I'll close this off then
