### ISSUE TITLE
Cut a new gem

### ISSUE THREAD

**Issue by albertyw** [rweng/jquery-datatables-rails#199]
There's been many commits since the last rubygems version (3.0.0), including several bugfixes.  Can someone please upload a new version onto rubygems?  It looks like it would be 3.0.1 or 3.1.0.

**Comment by steveo7** [comment]
+1 there are many good bug fixes in the latest commits, it would be great to have them on rubygems.  thanks so much for this gem

**Comment by mauntrelio** [comment]
+1
thanks a lot

**Comment by rweng** [comment]
3.4.0 was just released
