### ISSUE TITLE
get icons to show

### ISSUE THREAD

**Issue by logicminds** [rweng/jquery-datatables-rails#211]
Probably a dumb question but I cant get the icons to show up in the tables which give the user feedback that its a sortable column. Is there something we need to enable?

![screenshot 2016-06-09 16 09 27](https://cloud.githubusercontent.com/assets/563900/15949462/9154f44e-2e5c-11e6-8b99-4050048643a8.png)

**Comment by Shwetakale** [comment]
@logicminds I was facing the same issue. Columns were sortable but the icon to indicate that were missing. 

In my case classes were getting applied to DOM correctly but I css was not applied as I forgot to ```require``` datatable css in my ```application.css```. Adding following line in ```application.css``` solved my problem.

    *= require dataTables/bootstrap/2/jquery.dataTables.bootstrap

Hope this solves your problem too.

**Comment by logicminds** [comment]
yep that solved the problem.
