### ISSUE TITLE
Cannot reinitialise DataTable, when using Twitter Bootstrap

### ISSUE THREAD

**Issue by faceyspacey** [rweng/jquery-datatables-rails#32]
I'm getting the below error message when using twitter bootstrap:

DataTables warning (table id = 'products'): Cannot reinitialise DataTable.

To retrieve the DataTables object for this table, pass no arguments or see the docs for bRetrieve and bDestroy

**Comment by devprakashbinary** [comment]
$('#dataTable').dataTable({
    ...
    ....
    "bDestroy": true
});
try this one
